### ISSUE TITLE
Building a fat APK fails

### ISSUE THREAD

**Issue by houdayec** [microsoft/fluentui-system-icons#151]
I am trying to build a simple fat APK to do some tests. Build fails when trying to run fluent-icons font subset.

I could pass this issue by adding `--no-tree-shake-icons`, but I would like to know where does this issue might come from.

Flutter SDK version used:

```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (4 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

Here are the failure logs I get when running `flutter build apk`

```
[  +74 ms] [ +107 ms] Using output file: /Users/houdayec/Work/dev/Mate/mate_app/build/app/intermediates/flutter/release/flutter_assets/packages/fluentui_system_icons/fonts/FluentSystemIcons-Regular.ttf
[        ]            Using source file: /Users/houdayec/Development/flutter/.pub-cache/hosted/pub.dartlang.org/fluentui_system_icons-1.1.89/lib/fonts/FluentSystemIcons-Regular.ttf
[        ] [   +2 ms] Codepoint 62573 not found in font, aborting.
[+37296 ms] [+37252 ms] android_aot_release_android-arm64: Complete
[ +101 ms] [ +142 ms] android_aot_release_android-x64: Complete
[  +99 ms] [  +63 ms] android_aot_release_android-arm: Complete
[ +199 ms] [ +186 ms] Persisting file store
[        ] [  +12 ms] Done persisting file store
[        ] [  +15 ms] Target aot_android_asset_bundle failed: IconTreeShakerException: Font subsetting failed with exit code 255.
[        ]            To disable icon tree shaking, pass --no-tree-shake-icons to the requested flutter build command
[        ]            #0      IconTreeShaker.subsetFont (package:flutter_tools/src/build_system/targets/icon_tree_shaker.dart:217:7)
[        ]            #1      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #6      Future._complete (dart:async/future_impl.dart:519:7)
[        ]            #7      Stream.fold.<anonymous closure> (dart:async/stream.dart:847:14)
[   +2 ms]            #8      _rootRun (dart:async/zone.dart:1182:47)
[        ]            #9      _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #11     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
[        ]            #12     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
[        ]            #13     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
[        ]            #14     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
[        ]            #15     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
[        ]            #16     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
[  +16 ms]            #17     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
[        ]            #18     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
[        ]            #19     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
[        ]            #20     _rootRun (dart:async/zone.dart:1182:47)
[        ]            #21     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #22     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #23     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
[        ]            #24     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
[        ]            #25     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
[  +12 ms]            #26     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
[        ]            #27     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
[        ]            #28     _StreamController.close (dart:async/stream_controller.dart:664:5)
[        ]            #29     _Socket._onData (dart:io-patch/socket_patch.dart:2051:21)
[        ]            #30     _rootRunUnary (dart:async/zone.dart:1206:13)
[        ]            #31     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[        ]            #33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
[        ]            #34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
[   +4 ms]            #35     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
[        ]            #36     _StreamController._add (dart:async/stream_controller.dart:682:7)
[        ]            #37     _StreamController.add (dart:async/stream_controller.dart:624:5)
[        ]            #38     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1587:35)
[        ]            #39     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1069:18)
[        ]            #40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ]            #41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ]            #42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[   +1 ms]            #43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[        ] [   +4 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:238:7)
[        ]            #2      _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +4 ms]            #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #11     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +7 ms]            #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #20     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[   +3 ms]            #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #26     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[        ]            #27     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #29     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #31     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #32     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[   +3 ms]            #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #35     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ]            #36     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #42     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[   +7 ms]            #43     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #44     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #45     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #47     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #48     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #49     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #50     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #51     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
[   +8 ms]            #52     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #53     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #54     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #55     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #56     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #57     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #58     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #59     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[   +4 ms]            #60     FileStore.diffFileList (package:flutter_tools/src/build_system/file_store.dart)
[        ]            #61     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #62     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #63     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #65     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #66     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #67     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
[        ]            #68     _rootRunUnary (dart:async/zone.dart:1198:47)
[        ]            #69     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[   +4 ms]            #70     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #71     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #72     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #73     Future._completeWithValue (dart:async/future_impl.dart:529:5)
[        ]            #74     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
[        ]            #75     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
[        ]            #76     FileStore._hashFile (package:flutter_tools/src/build_system/file_store.dart)
[        ]            #77     _rootRunUnary (dart:async/zone.dart:1198:47)
[   +4 ms]            #78     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ]            #79     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
[        ]            #80     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
[        ]            #81     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
[        ]            #82     Future._complete (dart:async/future_impl.dart:519:7)
[        ]            #83     Stream.last.<anonymous closure> (dart:async/stream.dart:1327:20)
[        ]            #84     _rootRun (dart:async/zone.dart:1182:47)
[        ]            #85     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #86     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #87     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
[   +7 ms]            #88     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
[        ]            #89     _DelayedDone.perform (dart:async/stream_impl.dart:630:14)
[        ]            #90     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
[        ]            #91     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
[        ]            #92     _rootRun (dart:async/zone.dart:1182:47)
[        ]            #93     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #94     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #95     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ]            #96     _rootRun (dart:async/zone.dart:1190:13)
[   +2 ms]            #97     _CustomZone.run (dart:async/zone.dart:1093:19)
[        ]            #98     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
[        ]            #99     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
[        ]            #100    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ]            #101    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ]            #102    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ]            #103    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
[        ] [  +12 ms] "flutter assemble" took 102,149ms.
[        ] [   +1 ms] ensureAnalyticsSent: 0ms
[        ] [   +1 ms] Running shutdown hooks
[   +1 ms] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] > Task :app:compileFlutterBuildRelease FAILED
[  +77 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/houdayec/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command '/Users/houdayec/Development/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 47s

```

**Comment by spencer-nelson** [comment]
@aakash1313 or @willhou to confirm, but it looks to me like you are trying to use a codepoint that was either excluded from the subset or shaken out. In particular, the error references 0xf46d as the code point which is ic_fluent_hand_raise_24_regular. In your fat APK are you referencing that codepoint in a non-standard manner such that the tree shaking wouldn't have caught the use of it?

**Comment by houdayec** [comment]
I was still using `ic_fluent_hand_raise_24_regular` in an old part of my app. Indeed, I was able to choose it from `FluentIcons` class but nothing was shown on screen. Removed it and build passes without flag now, thanks.

Is there any way to find out which icon might be missing from the codepoint? Just in case other icons are removed / renamed in further versions.

**Comment by aakash1313** [comment]
It seems this issue is a duplicate of the below issues : 

https://github.com/flutter/flutter/issues/63357
 
https://github.com/flutter/flutter/issues/60325
 
https://github.com/flutter/flutter/issues/63
 
It is seen from the flutter version 20 and onwards and many people reported it after .There were some issues in the way tree shaking was done. It seems they fixed it in version 23 which is currently in beta channel.  So you can try two things for the time being until version 23 reaches stable , 
1. Disable tree-shaking as recommended by the flutter team and you already did. (--no-tree-shake-icons).
2. Remove the library, add it again , it should fix it for you. 

Hope that clarifies your doubt.

**Comment by houdayec** [comment]
Thanks for you answer, everything is clear now. I'm closing this issue as I don't need any more details.

**Comment by jamesblasco** [comment]
I am not sure if icons like `ic_fluent_hand_raise_24_regular` have been removed from the font. But if this is the case they should be reviewed and removed from the code. If there are not removed, then they should be fixed and added. 

There are so many of them that don't display. Here you can visually check them
https://jamesblasco.github.io/fluentui-system-icons/#/

I opened the issue #166 to follow the missing icons problem on the Flutter package

**Comment by houdayec** [comment]
> I am not sure if icons like `ic_fluent_hand_raise_24_regular` have been removed from the font. But if this is the case they should be reviewed and removed from the code. If there are not removed, then they should be fixed and added.
> 
> There are so many of them that don't display. Here you can visually check them
> https://jamesblasco.github.io/fluentui-system-icons/#/
> 
> I opened the issue #166 to follow the missing icons problem on the Flutter package

I completely agree with you, I'm running into this issue many times. Sometimes it is not even a name change but just a size change making for instance `FluentIcons.phone_28_regular` not found... Yes we should load the whole GitHub page, check for the icons one by one until we find `FluentIcons.phone_24_regular`.

Definitely annoying, such a shame because those icons are very good for UI.
